### ISSUE TITLE
Extend logout dialog to optionally delete cached data

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#108]
Once [OMEMO support](https://github.com/prose-im/prose-core-client/issues/19) lands, messages will be end-to-end encrypted when the feature is enabled.

This means that when a user logs out from the app and we delete their locally cached encryption keys and messages that they won't be able to decrypt/read them again on the same device when they log back in.

As such a user should make the decision if they want the cached data to be deleted or not. For this purpose the logout dialog should contain a checkbox.

Here's an idea for the label and an additional description:

```
[ ] Delete all cached data (including messages and encryption keys)

Note: Deleting cached data will permanently remove your messages from this device. You will not be able to read them when you log back in.
```

Cached data is now segregated by account since https://github.com/prose-im/prose-core-client/commit/1f4c1d3219bca71f9640a044d2fe31cdc7cf418f. This also means that we could support multiple simultaneous accounts from a data storage point of view.

**Comment by poVoq** [comment]
Might be a bit confusing for non-encrypted messages that will be readable again just fine. Maybe add "decrypted" somewhere in the note?
