### ISSUE TITLE
Notifications should include room info

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#110]
Currently when receiving a message notification it includes the sender name and the body of the message, which is great for direct messages. For groups or channels however it makes the notification look as if the message was sent to you personally. In these cases it would make sense to include the name of the room the message was sent to.

**Comment by valeriansaliou** [comment]
![Screenshot 2024-06-16 at 11 05 27 PM](https://github.com/prose-im/prose-app-web/assets/1451907/871ba509-d2fc-4916-a6c2-24b432148338)

Here's how it looks now if the room name doesn't match the message sender name (ie. not a DM).

**Comment by nesium** [comment]
Thanks!

I'm assuming we can't set a subtitle?

![387877](https://github.com/prose-im/prose-app-web/assets/39174/220e45ba-c7c0-4819-8cc5-88c26d5e098d)

**Comment by nesium** [comment]
Apparently not: https://github.com/tauri-apps/plugins-workspace/blob/7d332ef63428475852d053cd4edc85c49a3a6faa/plugins/notification/ios/Sources/Notification.swift#L32

Makes me want to fork the plugin

**Comment by nesium** [comment]
What about "Valerian Saliou @ general"? So that we have more room for the body.

**Comment by valeriansaliou** [comment]
This is @dscso plugin, you may check here: `notifications = { git = "https://github.com/dscso/mac-notifications.git", rev = "c7788fc" }`

**Comment by valeriansaliou** [comment]
![Screenshot 2024-06-17 at 11 43 39 AM](https://github.com/prose-im/prose-app-web/assets/1451907/1ae2dc87-13af-4d4f-8fdd-657d1ad73e25)

Does it look better now?

**Comment by nesium** [comment]
I also like the version with "Name (Room)" better. The "mac-notifications" plugin/repo uses `NSUserNotification` which has been deprecated since [quite a while](https://developer.apple.com/documentation/foundation/nsusernotification). Might make sense to switch to the newer `UNNotificationRequest` which then would also allow using subtitles.

**Comment by dscso** [comment]
I didn't have the time to port the notification library to UNNotification. There is some draft which I can use, but it is not finished yet.
