### ISSUE TITLE
Prosody team says we should implement XHTML-IM instead of sending Markdown

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-web#114]
![Screenshot 2024-06-19 at 11 42 38](https://github.com/prose-im/prose-app-web/assets/37386490/fec0a151-0181-4b6b-81f4-a50f8428c4f1)

> `@Link Mauve`, XEP-0071: XHTML-IM is deprecated. Was it superseded?

![Screenshot 2024-06-19 at 11 43 27](https://github.com/prose-im/prose-app-web/assets/37386490/bfca2d7f-3521-419b-a0f9-3e07fa21cde6)

NOTE: I'm creating the issue here because it's about the client, even though it might make sense to put it into prose-core-client too. Feel free to move it.

**Comment by poVoq** [comment]
This is debatable. Sending plain Markdown like Prose currently does degrades better and also works much better via bridges to other major team-chat platforms that all support plain Markdown (except Matrix which uses a HTML mess).

**Comment by RemiBardon** [comment]
@poVoq Fair point.

What do you mean by "does degrades better"?

**Comment by poVoq** [comment]
Markdown text in clients not implementing a markdown parser is still pretty readable and the overall intend is mostly understandable.

AFAIK xHTML-im does support a plaintext fallback, but then any formatting is lost completely if a client does not implement a HTML parser.

I think the compromise XEP is this: https://xmpp.org/extensions/xep-0481.html

**Comment by RemiBardon** [comment]
Well it's exactly what's being said in [Prose's #general MUC](xmpp:org.prose.channel.5n6mqquv@groups.prose.org) 😌

**Comment by valeriansaliou** [comment]
Closing this one for now, since we opted for XEP-0393 and XEP-0481.
