### ISSUE TITLE
Descenders of large fonts truncated in message

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#119]
<img width="575" alt="Screenshot 2024-06-27 at 10 17 04" src="https://github.com/prose-im/prose-app-web/assets/39174/b2e8fb81-ee72-44c5-b404-292752b74af5">

Message here was:

```
List registered users:

# prosodyctl shell user list example.tld
```

Debatable if we even want to support different font sizes in a message.

**Comment by valeriansaliou** [comment]
I've addressed this by normalizing all title font sizes to the normal message font size. There's no practical need to have different font sizes in messages, it's rather an annoyance.
