### ISSUE TITLE
Support host-meta.json

### ISSUE THREAD

**Issue by raucao** [prose-im/prose-app-web#121]
We only offer the JSON/JRD URL for our XMPP service, which is easier to parse from TypeScript/JavaScript anyway. The format is specified in the same RFC as the XML version. This means the web app currently doesn't work for our accounts.

Would be good to support the JRD endpoint, either in addition to the XML endpoint, or in place of it.

Example: https://kosmos.org/.well-known/host-meta.json

**Comment by valeriansaliou** [comment]
Thank you for the report, secondary support for JRD host-meta files has been added in df5fdc88214a731dce418ceb722f811520bc885f

Let me know if that works for you.
