### ISSUE TITLE
Use name instead of JID when displaying reactions

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#122]
At least I believe that that's the reason…

<img width="476" alt="Screenshot 2024-07-02 at 14 34 11" src="https://github.com/prose-im/prose-app-web/assets/39174/2e8f9c4f-8efa-452b-9d01-1fcb2d498b68">

<img width="599" alt="Screenshot 2024-07-02 at 14 35 52" src="https://github.com/prose-im/prose-app-web/assets/39174/ce6a2f04-5c6a-45e6-8b8b-0c3f22c3d2bd">

**Comment by valeriansaliou** [comment]
Should be fixed now.
