### ISSUE TITLE
Allow previewing message draft

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#142]
When composing larger messages it would be handy to see a preview of the rendered version of the message. I'd suggest that we implement this like here in Github issues instead of having a WYSIWYG editor like Slack.

Let me know if you agree @valeriansaliou, so I can add a method to transform a Markdown string to HTML.

**Comment by valeriansaliou** [comment]
This sounds good to me, definitely not liking Slack's WYSIWYG editor so I'm open to a GH-like editor.

**Comment by nesium** [comment]
`ProseClient` now contains

```ts
previewMarkdown(markdown: string): string;
```

**Comment by valeriansaliou** [comment]
Implemented!

<img width="911" alt="Screenshot 2024-11-27 at 6 32 21 PM" src="https://github.com/user-attachments/assets/2e5e09f8-59cf-42aa-b72a-c6cdf573459e">
