### ISSUE TITLE
Support looking for host-meta at port 5281 (support for mod_http_altconnect)

### ISSUE THREAD

**Issue by derspyy** [prose-im/prose-app-web#146]
i have a server running at https://capivarinha.club/ and prosody on the same IP address.

when Prose tries fetching my host-meta on login, though, it checks https://capivarinha.club, even though the http server for prosody is hosted at https://capivarinha.club:5281/ (which is currently serving the correct host-meta).

now, i'm not super familiar with how prose finds this URL, but would it be possible to support for this, at least as a fallback?

i'm using this module: https://modules.prosody.im/mod_http_altconnect

**Comment by valeriansaliou** [comment]
Hello! Prose requires this host-meta file to be located on your domain over HTTPS port 443. You may create a `.well-known/` folder at the root of your main Web server (not the XMPP HTTP server, your NGINX or Apache Web server), and place your `host-meta` file here so that Prose can fetch it at: `https://capivarinha.club/.well-known/host-meta` (if XML) or `https://capivarinha.club/.well-known/host-meta.json` (if JSON).

**Comment by derspyy** [comment]
yes. what i mean is that host-meta is already managed by another service and i'd prefer if it looked at the https server provided by prosody

**Comment by valeriansaliou** [comment]
Prose is implementing https://xmpp.org/extensions/xep-0156.html in a strict sense, which does not mention using any alternative port, so the standard is to use the default HTTPS port, that is `443`. You could easily setup a reverse proxy from your primary HTTPS server to port `5281` to serve the host-meta file from there.

**Comment by derspyy** [comment]
if we're being strict, shouldn't host-meta only be used as a fallback in case prose doesn't find bosh and websocket in the default paths? (or am i misunderstanding???)

**Comment by poVoq** [comment]
Port 5280/5281 isn't really standardized for XMPP servers, Ejabberd for example defaults to 5433, and most servers do indeed reverse-proxy it onto the standard port 443.

Adding the XEP-0156 host-meta files seems to not interfere with my other stuff on the same domain, so you should be good to try.

**Comment by derspyy** [comment]
yeah, thanks :P 

i just though it'd be a bit too risky to overwrite host-meta when it's managed by my service

**Comment by derspyy** [comment]
thx everyone! closing because i decided to do this on my nginx config.
