### ISSUE TITLE
`'` becomes `’` or a `‘` even in code blocks

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-web#148]
Every time I put a `'` inside backticks, it gets transformed into a `’` or a `‘` by my Mac. It’s a normal behavior on a Mac but it's really annoying when copy-pasting code. We should disable this behavior in the text field or even better find a way to disable it only in code blocks.

By the way, GitHub disabled it altogether when creating an issue for example (possibly everywhere).

**Comment by valeriansaliou** [comment]
I've tested and it seems to only happen in the Tauri build, which uses a Safari-based Web View. It does not happen in the exact same release of Prose in Safari itself, nor does it happen in Firefox. I'm quite puzzled by this behavior 🤷‍♂️

**Comment by valeriansaliou** [comment]
Found a way, this seems fixed in a local Tauri dev build :)
