### ISSUE TITLE
Invalid credentials are not reported as such on login

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#16]
The problem is that Strophe.js doesn't seem to properly report that situation. Instead it reports the more generic `Strophe.Status.CONNFAIL`. This currently has the effect that we switch from login to inbox without a valid connection.

**Comment by valeriansaliou** [comment]
Mhhh I used to receive an AUTHFAIL on the pure JS implementation, maybe something the core-client can pass?

**Comment by nesium** [comment]
Oh, you're right. I just had in mind that the web app hung before the change when trying to connect with invalid credentials. I'll try to surface the correct error then. What I was actually doing was trying to connect to a local server and that failed with `CONNFAIL`. Error handling should definitely be more robust here.

**Comment by valeriansaliou** [comment]
Updating this issue since this is an "important" one, could I maybe get the rejection error as an ENUM with common login failure reasons that I can handle?

**Comment by nesium** [comment]
Added. You can now handle the error [here](https://github.com/prose-im/prose-app-web/blob/ac4e839f4734a10e5697873deb5b951961749485/src/broker/client.ts#L179).

**Comment by valeriansaliou** [comment]
Considering this one as closed now.
