### ISSUE TITLE
User activity is not restored after logout/login

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-web#18]
The server should announce our own activity over PEP upon login (from logout or from session restore). The current activity should be restored in the UI accordingly. This used to work w/ the pure-JS backend.

**Comment by nesium** [comment]
Feels related to the discussion in #4. Makes total sense to pull the logic into the core where we can add tests that all consumers benefit from.

**Comment by nesium** [comment]
Reopening since I confused Availability (Presence) and User Activity
