### ISSUE TITLE
Support referring (@) to other users

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#23]
When typing @ into the chat textfield a popover with the list of contacts should appear and allow the user to select a contact from the list.

API-wise it would probably make sense to pass the referenced contact from the UI to the core lib similar to the Crisp API.

[Related core lib issue](https://github.com/prose-im/prose-core-client/issues/27)

**Comment by valeriansaliou** [comment]
@nesium UI is ready. I can pass a JID to the core client when there are mentions in a message, waiting for your directives :)

**Comment by nesium** [comment]
We could replace `@user` with a [XMPP IRI](https://xmpp.org/rfcs/rfc4622.html) wrapped in Markdown, i.e. `[Valerian](xmpp:valerian@prose.org)`. After parsing these could be formatted again, while providing the old value as a fallback.

I was also wondering if we could do the markdown parsing in the core (https://github.com/raphlinus/pulldown-cmark) and output a simple JSON format that only would need to be styled. Although as long as we don't want to display a message outside of the prose-core-view it could as well live on the JS side. I would just like to have a single message parsing routine (unlike Crisp).

**Comment by valeriansaliou** [comment]
I also wanted to go for an XMPP IRI as you’ve proposed. On Markdown parsing I’d rather leave this in the views, which is already what’s being done currently.

**Comment by valeriansaliou** [comment]
Thanks, will implement this weekend.
