### ISSUE TITLE
Use availability embedded in ParticipantInfo

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#28]
There are a couple of changes in the latest core lib: https://gist.github.com/nesium/f1c21dfb0d345b8c223017f418343a4e/revisions

`members` and `occupants` in `Room` have been merged into a single property `participants` (I've already changed that [here](https://github.com/prose-im/prose-app-web/commit/531dad85f866a0521e6399144649517c62fcc4a7)) which is an array of `ParticipantInfo`s.

Most importantly `ParticipantInfo::jid` is optional to honor the fact that MUC rooms can be anonymous and we might not know the real JID of a participant.

```ts
export class ParticipantInfo {
  free(): void;

  readonly affiliation: number;
  readonly availability: number;
  readonly isSelf: boolean;
  readonly jid: JID | undefined;
  readonly name: string;
}
```

`isSelf` might be handy for displaying purposes, but `affiliation` should probably be ignored until we have figured out our permissions system.

Also `destroyRoom` is now public on `ProseClient`…

```ts
* Destroys the room identified by `room_jid`.
* @param {JID} room_jid
* @returns {Promise<void>}
*/
  destroyRoom(room_jid: JID): Promise<void>;
/**
```

There's also a [new event handler](https://github.com/prose-im/prose-app-web/commit/96aa1ef9295e7b260b2fbeab4f3d8a68bb8a0399) `roomParticipantsChanged` that is called when the list of participants of a room is changed in some way (user joins/is kicked, etc.)

**Comment by valeriansaliou** [comment]
Upon calling `destroyRoom` I'm getting the following error:

```
[ERROR] Failed deleting channel Error: Room is already connected (org.prose.channel.viegfr7m@groups.prose.org.local).
```

Could the `destroyRoom` method be adjusted so that the room is left before it gets destroyed, so that the implementor doesn't have to handle the complexity of leaving before destroying? (and complexity of failure recovery if room is left but then removal fails, then we'd be left in a dangling state)

**Comment by valeriansaliou** [comment]
`roomParticipantsChanged` delegate event handler OK.

**Comment by nesium** [comment]
A couple of things went wrong here:
- When destroying a room I didn't remove it from the sidebar but merely set its status to 'disconnected with an error'
- I had a bug in the Wasm translation for the 'disconnected with error' state, instead it would then show as 'connecting'
- You're calling [`join`](https://github.com/prose-im/prose-app-web/blob/8840f6d9a57f259d92561445e4e8062a9117a669/src/components/popups/inbox/ManageMultiSettings.vue#L255) instead of `destroyRoom`

**Comment by valeriansaliou** [comment]
Thanks, bumped the core client library and it's now working.

Oops on the `join()` call, this was a typo. I tested with `destroyRoom()` right before refactoring to the current state, the error was there.

It's now working, thanks!
