### ISSUE TITLE
Sidebar sorting is not stable

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#34]
If you have two or more DM chats with identically named contacts the sort order occasionally changes when the sidebar is updated.

**Comment by valeriansaliou** [comment]
There’s no sorting AFAIK, that’s why. Will add, maybe showing DMs first (alphabetically?), then groups then channels.

**Comment by nesium** [comment]
Oh, I just assumed that it was sorted since it is already split up in different categories (Favorites, Direct Messages, Channels).
