### ISSUE TITLE
Roster load storm on startup

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-web#37]
When the Prose app starts, I receive multiple `contactChanged` and `roomsChanged` events, leading to local roster invalidation and reload. This ultimately leads to the app requesting the roster multiple times to the server in parallel.

- Is there any issue where I am receiving those delegate events from the core client more than I should?
- Or should this be handled in the application, eg. by debouncing the load or changing the roster reload mechanics, eg. not reloading on those events and completely de-correlating the roster from those events?
- Would that have any impact on rooms?

Those screenshots show the event/stanza storm on startup, which happen in a second or so:

![image](https://github.com/prose-im/prose-app-web/assets/1451907/104927b7-c0e4-4396-aad4-8c5ae8730580)
![image](https://github.com/prose-im/prose-app-web/assets/1451907/9f0b7c4a-4af7-48dc-8cac-9f39920ab4e3)

**Comment by valeriansaliou** [comment]
Poke @nesium

**Comment by nesium** [comment]
I had that on my list for a while. I'll give it a go. Would like to handle it in the core.

**Comment by valeriansaliou** [comment]
Perfect, sounds good yes!

**Comment by nesium** [comment]
Events are now throttled and coalesced. Please note the slight change in the delegate signature:

<img width="431" alt="Screenshot 2024-02-05 at 19 32 56" src="https://github.com/prose-im/prose-app-web/assets/39174/3f69d67c-d89b-43ce-a4ba-9dd83c354ea3">
