### ISSUE TITLE
Sidebar doesn't update after joining a room

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#39]
I had a MUC room selected, clicked "Add a channel" to join another existing MUC room. The (left) sidebar updated correctly with the new room selected, the messages area also showed the correct messages for the new room. The info bar on the right however still displayed the info of the former selected room.

**Comment by nesium** [comment]
Maybe that was due to a prior exception?

**Comment by valeriansaliou** [comment]
Currently, there’s no exception handling on this one AFAIK. What was the error?

**Comment by nesium** [comment]
I'm not sure but in general all of the core client methods can throw when an error occurs. But I'm definitely seeing the need to do some more real world testing on my side…
