### ISSUE TITLE
Displayed date seems to be off by one day

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#40]
<img width="1429" alt="Screenshot 2024-02-08 at 11 12 50" src="https://github.com/prose-im/prose-app-web/assets/39174/5764c536-5bc3-4e26-9f79-f31b02e363bc">

It would also be nice to see the full date as a tooltip when hovering over the time of a message so that you don't have to scroll all the way up to figure out the date when more than a few message were sent on the same day.

**Comment by valeriansaliou** [comment]
Fixed. The full message date will be shown as part of #41
