### ISSUE TITLE
Messages still (somewhat) visible after leaving a room

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#47]
I'm not sure if this is as intended, it looks like a bug to me. When you leave a room you can still see its messages shining through under the placeholder image…

<img width="1119" alt="Screenshot 2024-02-19 at 15 21 51" src="https://github.com/prose-im/prose-app-web/assets/39174/09412c94-3ab1-47e4-a7d7-0b701ed0892e">

**Comment by valeriansaliou** [comment]
Indeed, in this situation anyways, I think I should:

1. Flush the `$inbox` store for the `RoomID`
2. Navigate out of the room that was just left
