### ISSUE TITLE
Provide stream features from strophe.js

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#57]
This is required to determine server capabilities.

core-lib API is TDB in https://github.com/prose-im/prose-core-client/issues/23

Refs:
- https://xmpp.org/extensions/xep-0198.html#feature
- https://xmpp.org/registrar/stream-features.html

**Comment by valeriansaliou** [comment]
So, I've just checked and I'm already passing the `<stream:features />` stanza to the core's `eventHandler.handleStanza()`.

The stanza looks as such, and contains the capabilities hash, as well as stream-level server features:

```xml
<stream:features xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'><c node='http://prosody.im/' xmlns='http://jabber.org/protocol/caps' hash='sha-1' ver='SLdyYk4wQZVH/ipEJlOyN2Kyhdk='/><csi xmlns='urn:xmpp:csi:0'/><ver xmlns='urn:xmpp:features:rosterver'/><sm xmlns='urn:xmpp:sm:2'><optional/></sm><sm xmlns='urn:xmpp:sm:3'><optional/></sm><sub xmlns='urn:xmpp:features:pre-approval'/><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><required/></bind><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session><limits xmlns='urn:xmpp:stream-limits:0'><max-bytes>262144</max-bytes></limits></stream:features>
```

**Comment by nesium** [comment]
Oh, thank you! I didn't notice. It's somewhat more difficult in xmpp-rs so I thought it would be the same with strophe.js as well. I'll take care of passing that to the core myself and will close this in favor of the mentioned prose-im/prose-core-client#23
