### ISSUE TITLE
Support discovering the websocket address automatically

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#58]
While I'm at it…

As a user I want to use the Prose web app to connect to my accounts on various different servers. At the moment however the websocket address is hard-coded in the `config/*.json` files.

To mitigate that we should implement [XEP-0156: Discovering Alternative XMPP Connection Methods](https://xmpp.org/extensions/xep-0156.html).

Here's an article that outlines a few different methods to support it on the server: https://community.hetzner.com/tutorials/prosody-debian9#xep-0156-discovering-alternative-xmpp-connection-methods-http

**Comment by valeriansaliou** [comment]
I've added the following files on `prose.org`:

- https://prose.org/.well-known/host-meta.json
- https://prose.org/.well-known/host-meta

CORS OK, and HTTP Content-Type OK. Let me know if this works for you.

**Comment by valeriansaliou** [comment]
Sure, will do this weekend!
