### ISSUE TITLE
Missing initial for participants with a single letter name

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#59]
<img width="171" alt="Screenshot 2024-02-23 at 14 14 58" src="https://github.com/prose-im/prose-app-web/assets/39174/b6d57aad-7566-4ddc-bbf4-8abc3c14d5b4">

Corner cases! 🎉

**Comment by nesium** [comment]
The new colored icons look really nice though! Is this according to [XEP-0392](https://xmpp.org/extensions/xep-0392.html)? We should probably move the color generation into the core since it will be needed on other clients as well.

What also would be a nice touch btw. is if we could see the real jid (if available) on hover. Or even better if we had a universal tooltip that whould show information about a contact.

**Comment by valeriansaliou** [comment]
- I didn't use XEP-0392 to generate avatar colors, rather my own method. I'll see if I can adjust to this XEP.
- Will see what I can do to show more informations on hover.
- Will fix the single-initial bug. Thanks!
