### ISSUE TITLE
Make sure disco info, entity time, software version and so on are on-par w/ the state of the previous pure-JS implementation

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-web#7]

**Comment by nesium** [comment]
Software version can now be set [via the ProseClientConfig](https://github.com/prose-im/prose-core-client/commit/9dbcb2d9cf71914b79c43d3bbbedaeccc8992e0a).

**Comment by valeriansaliou** [comment]
All good now.
