### ISSUE TITLE
Identify rooms from external servers in the sidebar (DMs, channels, groups)

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-web#79]
![image](https://github.com/prose-im/prose-app-web/assets/1451907/8826cde7-6ad7-461d-82b5-5c09859b393a)

**Comment by nesium** [comment]
What could work as well is to leave DMs as-is, since you're usually aware what company a contact belongs to, or maybe just add a small symbol to the avatar image.

**Comment by nesium** [comment]
<img width="294" alt="Screenshot 2024-05-29 at 18 58 03" src="https://github.com/prose-im/prose-app-web/assets/39174/e539893d-0023-4d6a-a25a-c645bde43c2f">

Maybe the server name could go in a second line? Or at least be fully visible in a tooltip.
