### ISSUE TITLE
Scrollbar runs behind sidebar footer

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#86]
A bit of a nitpick, but it looks even weirder with the new blurred background…

<img width="95" alt="Screenshot 2024-04-05 at 13 54 35" src="https://github.com/prose-im/prose-app-web/assets/39174/9605b408-2588-4641-a359-27ed6d75435d">

What it should look like…

![Slice 1](https://github.com/prose-im/prose-app-web/assets/39174/2b0180de-09a3-4107-be79-04f42acdbc3f)

I think I wouldn't let content run behind the footer so that it doesn't have the blur smudges.

**Comment by valeriansaliou** [comment]
Unfortunately I'd like to keep the style where the header is above the content and therefore blurry above the content. I did not find a way to offset the scroll bar only, in a way that the scrollable content can flow below the header, but the scrollbar top position is offset vertically by the header height.
